// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProF.Data;

#nullable disable

namespace ProF.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    partial class ApplicationDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentRegisteration_USER_", b =>
                {
                    b.Property<int>("PaymentsPayment_Id")
                        .HasColumnType("int");

                    b.Property<int>("Registeration_USER_sRegister_id")
                        .HasColumnType("int");

                    b.HasKey("PaymentsPayment_Id", "Registeration_USER_sRegister_id");

                    b.HasIndex("Registeration_USER_sRegister_id");

                    b.ToTable("PaymentRegisteration_USER_");
                });

            modelBuilder.Entity("ProF.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("RegisterId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ProF.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("item_Cost")
                        .HasColumnType("real");

                    b.Property<string>("item_image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ProF.Models.Order", b =>
                {
                    b.Property<int>("order_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_num"));

                    b.Property<string>("Order_DateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity_of_each_recipe")
                        .HasColumnType("int");

                    b.Property<string>("Recipes_Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Register_id")
                        .HasColumnType("int");

                    b.Property<int>("Registeration_USER_Register_id")
                        .HasColumnType("int");

                    b.HasKey("order_num");

                    b.HasIndex("Registeration_USER_Register_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProF.Models.Payment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<int?>("order_num")
                        .HasColumnType("int");

                    b.Property<int>("t_p")
                        .HasColumnType("int");

                    b.HasKey("Payment_Id");

                    b.HasIndex("order_num");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ProF.Models.Registeration_USER_", b =>
                {
                    b.Property<int>("Register_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Register_id"));

                    b.Property<DateTime>("Register_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("table_num")
                        .HasColumnType("int");

                    b.HasKey("Register_id");

                    b.ToTable("Registeration_USER_");
                });

            modelBuilder.Entity("ProF.Models.Table", b =>
                {
                    b.Property<int>("table_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("table_num"));

                    b.Property<string>("class_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("table_num");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("ProF.Models.comment", b =>
                {
                    b.Property<int>("coment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("coment_id"));

                    b.Property<string>("coment_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("coment_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("ProF.Models.item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_id"));

                    b.Property<int>("adminID")
                        .HasColumnType("int");

                    b.Property<int>("category")
                        .HasColumnType("int");

                    b.Property<float>("item_Cost")
                        .HasColumnType("real");

                    b.Property<string>("item_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stars")
                        .HasColumnType("int");

                    b.HasKey("item_id");

                    b.HasIndex("adminID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("ProF.Models.login_admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("login_admins");
                });

            modelBuilder.Entity("Registeration_USER_Table", b =>
                {
                    b.Property<int>("Registeration_USER_sRegister_id")
                        .HasColumnType("int");

                    b.Property<int>("Tablestable_num")
                        .HasColumnType("int");

                    b.HasKey("Registeration_USER_sRegister_id", "Tablestable_num");

                    b.HasIndex("Tablestable_num");

                    b.ToTable("Registeration_USER_Table");
                });

            modelBuilder.Entity("Registeration_USER_comment", b =>
                {
                    b.Property<int>("Registeration_USER_sRegister_id")
                        .HasColumnType("int");

                    b.Property<int>("commentscoment_id")
                        .HasColumnType("int");

                    b.HasKey("Registeration_USER_sRegister_id", "commentscoment_id");

                    b.HasIndex("commentscoment_id");

                    b.ToTable("Registeration_USER_comment");
                });

            modelBuilder.Entity("PaymentRegisteration_USER_", b =>
                {
                    b.HasOne("ProF.Models.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentsPayment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProF.Models.Registeration_USER_", null)
                        .WithMany()
                        .HasForeignKey("Registeration_USER_sRegister_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProF.Models.CartItem", b =>
                {
                    b.HasOne("ProF.Models.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("ProF.Models.Order", b =>
                {
                    b.HasOne("ProF.Models.Registeration_USER_", "Registeration_USER_")
                        .WithMany("Orders")
                        .HasForeignKey("Registeration_USER_Register_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registeration_USER_");
                });

            modelBuilder.Entity("ProF.Models.Payment", b =>
                {
                    b.HasOne("ProF.Models.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("order_num");
                });

            modelBuilder.Entity("ProF.Models.item", b =>
                {
                    b.HasOne("ProF.Models.login_admin", "login_admin")
                        .WithMany("Items")
                        .HasForeignKey("adminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("login_admin");
                });

            modelBuilder.Entity("Registeration_USER_Table", b =>
                {
                    b.HasOne("ProF.Models.Registeration_USER_", null)
                        .WithMany()
                        .HasForeignKey("Registeration_USER_sRegister_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProF.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("Tablestable_num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Registeration_USER_comment", b =>
                {
                    b.HasOne("ProF.Models.Registeration_USER_", null)
                        .WithMany()
                        .HasForeignKey("Registeration_USER_sRegister_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProF.Models.comment", null)
                        .WithMany()
                        .HasForeignKey("commentscoment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProF.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProF.Models.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ProF.Models.Registeration_USER_", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ProF.Models.login_admin", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
